const pastas = [
  `Arteezy sat in a dark room. The words "Dire Victory" filled up the screen. Not even Arteezy's shadow fiend could win this game. 3/8/7 378 GPM. Tears filled Arteezy's eyes as he carassed his hand of midas. The sound of hard core gangster rap and crying filled the room. The door creaks open and EE-sama enters the room. "You lost Artour." "You do know what happens when you lose." Arteezy removed his clothes, wearing only one of EE's anime wigs. EE removed his clothes, "You lost 23 MM. Thats how many hours your punishment will be." Arteezy spent the next 23 hours being furiously ♥♥♥♥ed by his mentor. After the punishment the ♥♥♥♥♥ covered Arteezy arised. "Thank you master, I can't wait to return the favor when you lose." Envy smiled. "So will I Artour."`,
  `I owe my life to Arteezy. I got in a horrible car crash and i was in 6 month coma. The nurse switched to the Twitch channel to Arteezy's stream. I awoke from my coma and muted it.`,
  `ＨＥＹ　ＲＴＺ，　Ｉ’Ｍ　ＴＲＹＩＮＧ　ＴＯ　ＬＥＡＲＮ　ＴＯ　ＰＬＡＹ　ＲＩＫＩ．　Ｉ　ＪＵＳＴ　ＨＡＶＥ　Ａ　ＱＵＥＳＴＩＯＮ　ＡＢＯＵＴ　ＴＨＥ　ＳＫＩＬＬ　ＢＵＩＬＤ：　ＳＨＯＵＬＤ　Ｉ　ＭＡＸ　ＢＡＣＫＳＴＡＢ　ＬＩＫＥ　ＹＯＵ　ＢＡＣＫＳＴＡＢＢＥＤ　ＥＧ，　ＳＭＯＫＥＳＣＲＥＥＮ　ＳＯ　ＴＨＥＹ　ＭＩＳＳ　ＭＥ　ＬＩＫＥ　ＥＧ　ＭＩＳＳ　ＹＯＵ　７０％　ＯＦ　ＴＨＥ　ＴＩＭＥ，　ＯＲ　ＰＥＲＭＡＮＥＴ　ＩＮＶＩＳＩＢＩＬＩＴＹ　ＳＯ　Ｉ　ＣＯＵＬＤ　ＤＩＳＡＰＰＥＡＲ　ＬＩＫＥ　ＹＯＵ　ＤＩＳＡＰＰＥＡＲＥＤ　ＦＲＯＭ　ＥＧ`,
  `Singsing is everywhere. Singsing is all around us. Even now, in this very room. You can see Singsing when you look out your window or when you turn on your television. You can feel Singsing when you go to work… when you go to church… when you pay your taxes. Singsing is the world that has been pulled over your eyes to blind you from the truth. For my ally is the Singsing, and a powerful ally it is. Life creates it, makes it grow. Its energy surrounds us and binds us. Luminous doters are we, not this crude matter. You must feel the Singsing around you; here, between you, me, the tree, the rock, everywhere, yes. Even between the land and the stream.`,
  `My Name is Jacky Mao Also Known as EternalEnvy and I am a creepy guy. Some evening I was walking home and saw Arteezy ♥♥♥♥♥♥ a girl. She was crying for help. When the girl saw me she started to hide behind Arteezy back...`,
  `ʜᴇʟʟᴏ ʙᴜʟʟᴅᴏɢᴇ I ᴀᴍ ғᴀᴍᴏᴜs ᴘᴏʀɴ ᴅɪʀᴇᴄᴛᴏʀ, ᴛᴏɴʏ ᴘᴀsᴛᴇʀɪɴᴏ. ᴡᴇ ᴡᴏᴜʟᴅ ʟɪᴋᴇ ʏᴏᴜ ᴀɴᴅ sʜᴇᴇᴠᴇʀ ᴛᴏ ᴘᴀʀᴛɪᴄɪᴘᴀᴛᴇ ɪɴ ᴏᴜʀ ɴᴇᴡ ᴠɪᴅᴇᴏ " ʜᴏᴏᴋɪɴ' ɴ ᴊᴜᴋᴇɪɴ' " sʜᴇᴇᴠᴇʀ ᴡᴏᴜʟᴅ ʙᴇ ᴡɪɴᴅʀᴜɴɴᴇʀ ᴀɴᴅ ʏᴏᴜ sᴀʏ ɴᴏ ᴊᴜᴋᴇʀɪɴᴏ ᴀɴᴅ ʙᴀᴄᴋᴅᴏᴏʀ ʜᴇʀ.`,
  `I only get to have sex when Ayesee is casting. My girlfriends hears the ACCURATE FACTS and gets so turned on she has sex with the nearest human - luckily it's normally me. Thank you Ayesee!`,
  `"Wow, what an eventful night of casting. I'm going to go to bed, remember to close the stream!" Ben Wu said kindly. "No.. I will not close the stream. I will make them watch.." A menacing grin appeared on Zyori's face. "Not again.." a sweat dropped from Ben Wu's brow. "The world will watch me sniff..." Zyori said, dropping his jean shorts.`,
  `"Haha, what a great day of casting" Merlini proclaimed. "Yeah, we did awesome, bro. Give me a high five". Oh boy, not this again, thought Merlini. "Bro, we're so tight we don't need to high five". Yet Zyori insisted. "High five my hand bro". Merlini had no choice. Merlini's hand still smells like Zyori's balls to this day.`,
  `<:::::[]=¤༼ຈل͜ຈ༽ﾉ I am the knight of spamerino. Stand back foul moderino <:::::[]=¤༼ຈل͜ຈ༽ﾉ`,
  `Hello guys, I'm back from my 600 seconds timeout. During that time I was able to finish my 200 words essay on the topic of Nazi Germany. My thesis is that Hitler & Nazi beliefs are carried on by twitch tv Nazi moderators who like to act as if they themselves were literally Hitler. I think I should score at least 90 out of 100 points for that paper. Pls no coperino my paperino.`,
  `ᕙ༼ຈل͜ຈ༽ᕗ. ʜᴀʀᴅᴇʀ, ʙᴇᴛᴛᴇʀ, ғᴀsᴛᴇʀ, ᴅᴏɴɢᴇʀ .ᕙ༼ຈل͜ຈ༽ᕗ `,
  `/╲/\╭(◕◕◕益◕◕◕)╮/\╱\ The silk road beckons `,
  `Ｈｅｌｌｏ Ｉ＇ｍ Ｓｎｉｔｈ， ｐｌａｙｉｎｇ ｍｙ ２０２１４３ｔｈ ｇａｍｅ ｏｎ Ｃｈｅｎ． Ｅｖｅｎ ｔｈｏｕｇｈ ｉｔ＇ｓ ｔｈｅ ｏｎｌｙ ｈｅｒｏ Ｉ ｐｌａｙ Ｉ ｓｔｉｌｌ ｓｕｃｋ ａｔ ｉｔ． Ａｓ ａ ｃｏｍｐｅｎｓａｔｉｏｎ ｆｏｒ ｍｙ ｌａｃｋ ｏｆ ｓｋｉｌｌ Ｉ ａｍ ｇｏｉｎｇ ｔｏ ｂｕｙ ａｌｌ ｓｕｐｐｏｒｔ ｉｔｅｍｓ ａｎｄ ｇａｎｋ ｍｉｄ ａｔ ｌｖｌ ２ ａｎｄ ｆａｉｌ． Ｔｈａｎｋｓ ｆｏｒ ｌｉｓｔｅｎｉｎｇ`,
  `EleGiggle WHEN EleGiggle I EleGiggle TYPE EleGiggle DOTA EleGiggle IN EleGiggle LOL, I GET SILENCED SoBayed WHEN EleGiggle I EleGiggle TYPE EleGiggle LOL EleGiggle IN EleGiggle DOTA, EleGiggle MY EleGiggle HERO EleGiggle LAUGHS EleGiggle`,
  `Fucking AM picker, no skill" The flame only fuels me. "Wow, nice work AM you took racks" I don't need your praise peasant. I'm fucking Anti-mage. The rest of the my 'team' is irrelevant. They only get in the way of my goal. The enemy ancient.`,
  `Hi r/dota2, I'm learning to play Venomancer, but I'm unsure of the skill build. Should I max Venomous Gale, like the way you only seem to spew toxic shit out of your mouths, Poison Sting like how half the threads I see sting my eyes, or Plague Wards like how new posts constantly pop up and annoy the shit out of me. Thanks!`,
  ` ʕ ͡·ᴥ ͡· ʔ You've been visited by Hellbear Smasher of fortune. Clap your paws and copy paste this message 5 times without getting banned by mods and luck be with you for the next year ʕ ͡·ᴥ ͡· ʔ`,
  `Sodium, atomic number 11, was first isolated by Peter Dager in 1807. A chemical component of salt, he named it Na in honor of the saltiest region on earth, North America.`,
  `Hi, 4k player here who reported slahser. Slahser was our position 1 faceless void. He built a mek and had around 29 healing salves in his inventory. He would chrono both teams in the middle of a fight, salve his allies, pop mek, and proceeded to yell "SLAHSER'S WAY". We gave him position 1 farm so he could be a position 5.
   Granted, his unorthodox build worked and carried us to victory but I still felt it deserved a report.`,
  `( ͡°╭͜ʖ╮͡° ) DAY TUCKER NIGHT FUCKER ( ͡°╭͜ʖ╮͡° )`,
  `Learn the ways of the Russians, speak their language for a while, they might think you are one of them. Then maybe join their team, success might come and fighting for last drink of vodka will be your next objective. Do not give up, you have Dota tournament ahead of you. Then win TI1, but don't stop now, you have to go deeper. Spend 3 more years trying to solve the puzzle of russki power of motherland and then leave the team with full knowledge of understanding of strenght of ROSSIA and PROMISE URSELF THET YU WILL NEVER LOS TO RUS AND KNOW OF COLLAPSING STRONG EMPIRE OF RUSKILAND.
thats basically what I did`
];

exports.getPastas = function() {
  return pastas;
};